import { useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent,type WheelEvent as ReactWheelEvent } from 'react'
import { lines,stationById,stations,transferPairs } from '../data/metro'
import { useLanguage } from '../lib/i18n'
import type { LineId } from '../types'
import { Icon } from './Icon'
import { FULL_VIEW,MAP_ASPECT,buildLabelLayout,clampView,distance,lineIds,midpoint,roundedPath,viewForStations,type CanvasSize,type MapView,type Point } from './metroMapLayout'

interface Props{activeStationId?:string;routeStationIds?:string[];onStationClick:(stationId:string)=>void}

export const MetroMap=({activeStationId,routeStationIds=[],onStationClick}:Props)=>{
  const {language,stationName,lineName}=useLanguage()
  const [view,setView]=useState<MapView>(FULL_VIEW)
  const [focusedLine,setFocusedLine]=useState<LineId|'all'>('all')
  const [canvasSize,setCanvasSize]=useState<CanvasSize>({width:900,height:620})
  const [isFullscreen,setIsFullscreen]=useState(false)
  const svgRef=useRef<SVGSVGElement|null>(null),viewportRef=useRef<HTMLDivElement|null>(null),pointersRef=useRef(new Map<number,Point>()),gestureMovedRef=useRef(false),lastTapRef=useRef<{at:number;point:Point}|null>(null)
  const routeKey=routeStationIds.join(':'),routeSet=useMemo(()=>new Set(routeStationIds),[routeKey]),routeEndpoints=useMemo(()=>new Set(routeStationIds.length?[routeStationIds[0],routeStationIds.at(-1)!]:[]),[routeKey])
  const linePaths=useMemo(()=>Object.values(lines).map(line=>({line,path:roundedPath(line.stationIds.map(id=>{const station=stationById.get(id)!;return{x:station.mapX,y:station.mapY}}))})),[])
  const routeSegments=useMemo(()=>{const result=new Set<string>();Object.values(lines).forEach(line=>line.stationIds.slice(0,-1).forEach((id,index)=>{const next=line.stationIds[index+1];if(routeSet.has(id)&&routeSet.has(next))result.add(`${id}:${next}`)}));return result},[routeSet])
  const selectedLine=focusedLine==='all'?null:lines[focusedLine],zoomLevel=FULL_VIEW.width/view.width,zoomPercent=Math.round(zoomLevel*100)
  const {placedLabels,mapPixels,compactCanvas,isOverview,labelFontPx,labelLineHeightPx,labelStrokePx}=buildLabelLayout({activeStationId,routeSet,routeEndpoints,focusedLine,zoomLevel,view,canvasSize,stationName})
  const nodeRadius=mapPixels(isOverview&&compactCanvas?4.4:5.2),routeNodeRadius=mapPixels(6.4),activeNodeRadius=mapPixels(7.2),transferRadius=mapPixels(isOverview&&compactCanvas?8.6:10)

  useEffect(()=>{const element=viewportRef.current;if(!element||typeof ResizeObserver==='undefined')return;const update=()=>setCanvasSize({width:Math.max(1,element.clientWidth),height:Math.max(1,element.clientHeight)});update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect()},[])
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setIsFullscreen(false)};document.body.classList.toggle('map-fullscreen-open',isFullscreen);window.addEventListener('keydown',onKey);return()=>{document.body.classList.remove('map-fullscreen-open');window.removeEventListener('keydown',onKey)}},[isFullscreen])

  const zoomAround=(factor:number,clientPoint?:Point)=>setView(current=>{const rect=svgRef.current?.getBoundingClientRect(),ratioX=rect&&clientPoint?(clientPoint.x-rect.left)/rect.width:.5,ratioY=rect&&clientPoint?(clientPoint.y-rect.top)/rect.height:.5,anchorX=current.x+ratioX*current.width,anchorY=current.y+ratioY*current.height,width=current.width/factor,height=width/MAP_ASPECT;return clampView({x:anchorX-ratioX*width,y:anchorY-ratioY*height,width,height})})
  const resetMap=()=>{setFocusedLine('all');setView(FULL_VIEW)}
  const focusLine=(lineId:LineId|'all')=>{setFocusedLine(lineId);if(lineId==='all')return setView(FULL_VIEW);const next=viewForStations(lines[lineId].stationIds,80);if(next)setView(next)}
  const focusRoute=()=>{if(routeStationIds.length<2)return;const next=viewForStations(routeStationIds,125);if(next)setView(next)}
  const handleWheel=(event:ReactWheelEvent<SVGSVGElement>)=>{event.preventDefault();zoomAround(Math.exp(-event.deltaY*.00135),{x:event.clientX,y:event.clientY})}
  const handlePointerDown=(event:ReactPointerEvent<SVGSVGElement>)=>{if((event.target as Element).closest('.map-station'))return;event.currentTarget.setPointerCapture(event.pointerId);pointersRef.current.set(event.pointerId,{x:event.clientX,y:event.clientY});gestureMovedRef.current=false}
  const handlePointerMove=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!pointersRef.current.has(event.pointerId))return;const before=new Map(pointersRef.current);pointersRef.current.set(event.pointerId,{x:event.clientX,y:event.clientY});const rect=event.currentTarget.getBoundingClientRect();if(before.size===1){const previous=before.get(event.pointerId);if(!previous)return;const dx=event.clientX-previous.x,dy=event.clientY-previous.y;if(Math.abs(dx)+Math.abs(dy)>2)gestureMovedRef.current=true;setView(current=>clampView({...current,x:current.x-(dx/rect.width)*current.width,y:current.y-(dy/rect.height)*current.height}));return}const ids=[...before.keys()].slice(0,2);if(ids.length<2)return;const previousFirst=before.get(ids[0])!,previousSecond=before.get(ids[1])!,nextFirst=pointersRef.current.get(ids[0])!,nextSecond=pointersRef.current.get(ids[1])!,previousDistance=distance(previousFirst,previousSecond),nextDistance=distance(nextFirst,nextSecond);if(previousDistance<2||nextDistance<2)return;const previousCenter=midpoint(previousFirst,previousSecond),nextCenter=midpoint(nextFirst,nextSecond),factor=Math.min(1.22,Math.max(.82,nextDistance/previousDistance));gestureMovedRef.current=true;setView(current=>{const previousRatioX=(previousCenter.x-rect.left)/rect.width,previousRatioY=(previousCenter.y-rect.top)/rect.height,nextRatioX=(nextCenter.x-rect.left)/rect.width,nextRatioY=(nextCenter.y-rect.top)/rect.height,anchorX=current.x+previousRatioX*current.width,anchorY=current.y+previousRatioY*current.height,width=current.width/factor,height=width/MAP_ASPECT;return clampView({x:anchorX-nextRatioX*width,y:anchorY-nextRatioY*height,width,height})})}
  const releasePointer=(event:ReactPointerEvent<SVGSVGElement>)=>{const point={x:event.clientX,y:event.clientY},station=Boolean((event.target as Element).closest('.map-station'));pointersRef.current.delete(event.pointerId);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);if(event.pointerType!=='touch'||gestureMovedRef.current||station)return;const now=Date.now(),previous=lastTapRef.current;if(previous&&now-previous.at<330&&distance(previous.point,point)<34){zoomAround(1.45,point);lastTapRef.current=null}else lastTapRef.current={at:now,point}}
  const lineIsDimmed=(lineId:LineId)=>focusedLine!=='all'&&focusedLine!==lineId

  return <section className={`map-card map-card-v6 card ${isFullscreen?'is-fullscreen':''}`}>
    <header className="map-header map-header-v6"><div><span className="eyebrow">{language==='uk'?'Схема метро':'Metro map'}</span><h2>{language==='uk'?'Київський метрополітен':'Kyiv Metro'}</h2><p>{language==='uk'?'На загальному вигляді показані лише ключові назви. Решта з’являється без накладань під час наближення.':'The overview shows only key names. More labels appear without overlaps as you zoom.'}</p></div>{routeStationIds.length>1&&<button type="button" className="map-route-focus" onClick={focusRoute}><Icon name="route" size={17}/>{language==='uk'?'Показати маршрут':'Show route'}</button>}</header>
    <div className="map-line-toolbar" aria-label={language==='uk'?'Фільтр ліній':'Line filter'}><button type="button" className={focusedLine==='all'?'active':''} onClick={()=>focusLine('all')} aria-pressed={focusedLine==='all'}>{language==='uk'?'Уся схема':'Full map'}</button>{lineIds.map(id=><button type="button" className={focusedLine===id?'active':''} onClick={()=>focusLine(id)} aria-pressed={focusedLine===id} key={id}><i style={{background:lines[id].color}}/>{id}<span>{lines[id].stationIds.length}</span></button>)}</div>
    <div className="map-workspace"><div ref={viewportRef} className="map-viewport" role="region" aria-label={language==='uk'?'Інтерактивна схема метро':'Interactive metro map'}>
      <svg ref={svgRef} className={`metro-map metro-map-v6 ${isOverview?'is-overview':''}`} viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} preserveAspectRatio="xMidYMid meet" role="img" aria-label={language==='uk'?'Схема трьох ліній Київського метро':'Map of the three Kyiv Metro lines'} onWheel={handleWheel} onPointerDown={handlePointerDown} onPointerMove={handlePointerMove} onPointerUp={releasePointer} onPointerCancel={releasePointer}>
        <rect x="0" y="0" width="960" height="710" className="diagram-background"/><path d="M 695 -30 C 645 85 655 185 680 270 C 713 383 652 505 690 755" className="metro-river" vectorEffect="non-scaling-stroke"/><text x="696" y="170" className="river-label" style={{fontSize:mapPixels(10)}}>ДНІПРО</text>
        {linePaths.map(({line,path})=><g key={line.id} className={lineIsDimmed(line.id)?'is-dimmed':''}><path d={path} className="metro-line-halo" vectorEffect="non-scaling-stroke" style={isOverview&&compactCanvas?{strokeWidth:11}:undefined}/><path d={path} className="metro-line-base" style={{stroke:line.color,...(isOverview&&compactCanvas?{strokeWidth:7}:{})}} vectorEffect="non-scaling-stroke"/></g>)}
        {Object.values(lines).flatMap(line=>line.stationIds.slice(0,-1).map((id,index)=>{const next=line.stationIds[index+1];if(!routeSegments.has(`${id}:${next}`))return null;const from=stationById.get(id)!,to=stationById.get(next)!;return <g key={`route-${id}-${next}`}><line x1={from.mapX} y1={from.mapY} x2={to.mapX} y2={to.mapY} className="metro-route-halo" vectorEffect="non-scaling-stroke"/><line x1={from.mapX} y1={from.mapY} x2={to.mapX} y2={to.mapY} className="metro-line-active" style={{stroke:line.color}} vectorEffect="non-scaling-stroke"/></g>}))}
        {transferPairs.map(([firstId,secondId])=>{const first=stationById.get(firstId)!,second=stationById.get(secondId)!,active=routeSet.has(firstId)&&routeSet.has(secondId);return <g key={`${firstId}-${secondId}`}><line x1={first.mapX} y1={first.mapY} x2={second.mapX} y2={second.mapY} className="transfer-link-outline" vectorEffect="non-scaling-stroke"/><line x1={first.mapX} y1={first.mapY} x2={second.mapX} y2={second.mapY} className={`transfer-link ${active?'active':''}`} vectorEffect="non-scaling-stroke"/></g>})}
        {stations.map(station=>{const active=activeStationId===station.id,onRoute=routeSet.has(station.id),dimmed=lineIsDimmed(station.line)&&!onRoute,radius=active?activeNodeRadius:onRoute?routeNodeRadius:nodeRadius;return <g key={station.id} className={`map-station ${active?'active':''} ${onRoute?'on-route':''} ${dimmed?'is-dimmed':''}`} role="button" tabIndex={dimmed?-1:0} aria-label={`${stationName(station)}, ${lineName(station.line)}`} onPointerDown={event=>event.stopPropagation()} onClick={()=>onStationClick(station.id)} onKeyDown={event=>(event.key==='Enter'||event.key===' ')&&onStationClick(station.id)}>{station.transferTo&&<><circle cx={station.mapX} cy={station.mapY} r={transferRadius+mapPixels(2)} className="transfer-ring-outline"/><circle cx={station.mapX} cy={station.mapY} r={transferRadius} className="transfer-ring"/></>}<circle cx={station.mapX} cy={station.mapY} r={radius} className="station-node" style={{stroke:lines[station.line].color}} vectorEffect="non-scaling-stroke"/></g>})}
        <g className="map-label-layer" aria-hidden="true">{placedLabels.map(label=>{const widthMap=mapPixels(label.rect.right-label.rect.left),heightMap=mapPixels(label.rect.bottom-label.rect.top),plateX=label.placement.anchor==='start'?label.x-mapPixels(3):label.placement.anchor==='end'?label.x-widthMap+mapPixels(3):label.x-widthMap/2,plateY=label.y-mapPixels(labelFontPx*.9+2);return <g key={label.key}>{label.plate&&<rect x={plateX} y={plateY} width={widthMap} height={heightMap} rx={mapPixels(5)} fill="var(--surface)" fillOpacity={.9} stroke="var(--border)" strokeWidth={mapPixels(.7)}/>}<text x={label.x} y={label.y} textAnchor={label.placement.anchor} className={label.className} style={{fontSize:mapPixels(labelFontPx),strokeWidth:mapPixels(labelStrokePx)}}>{label.lines.map((line,index)=><tspan key={`${label.key}-${index}`} x={label.x} dy={index?mapPixels(labelLineHeightPx):0}>{line}</tspan>)}</text></g>})}</g>
      </svg>
      <div className="map-floating-controls" aria-label={language==='uk'?'Керування схемою':'Map controls'}><button type="button" onClick={()=>zoomAround(1.28)} aria-label={language==='uk'?'Збільшити':'Zoom in'}>+</button><span>{zoomPercent}%</span><button type="button" onClick={()=>zoomAround(.78)} aria-label={language==='uk'?'Зменшити':'Zoom out'}>−</button><button type="button" onClick={resetMap} aria-label={language==='uk'?'Показати всю схему':'Show full map'}><Icon name="refresh" size={18}/></button><button type="button" onClick={()=>setIsFullscreen(value=>!value)} aria-label={language==='uk'?'Повноекранний режим':'Fullscreen'}>⛶</button></div>
      <div className="map-gesture-hint" aria-hidden="true"><span>↔</span>{language==='uk'?'Рухайте':'Pan'}<span>⌕</span>{language==='uk'?'Наближайте':'Zoom'}</div>
    </div><aside className="map-line-panel" aria-label={selectedLine?lineName(selectedLine.id):(language==='uk'?'Лінії метро':'Metro lines')}>{selectedLine?<><header><span className="line-pill" style={{background:selectedLine.color}}>{selectedLine.id}</span><div><strong>{lineName(selectedLine.id)}</strong><small>{selectedLine.stationIds.length} {language==='uk'?'станцій':'stations'}</small></div></header><div className="map-line-stations">{selectedLine.stationIds.map((id,index)=>{const station=stationById.get(id)!;return <button type="button" className={`${activeStationId===id?'active':''} ${routeSet.has(id)?'on-route':''}`} onClick={()=>onStationClick(id)} key={id}><span className="map-line-order">{index+1}</span><span><strong>{stationName(station)}</strong><small>{language==='uk'?station.nameEn:station.name}</small></span><Icon name="chevron" size={17}/></button>})}</div></>:<div className="map-lines-overview"><span className="eyebrow">{language==='uk'?'Швидкий огляд':'Quick view'}</span><h3>{language==='uk'?'Три лінії':'Three lines'}</h3><p>{language==='uk'?'Оберіть лінію, щоб залишити на схемі лише її та відкрити список станцій.':'Choose a line to isolate it on the map and open its station list.'}</p>{lineIds.map(id=><button type="button" onClick={()=>focusLine(id)} key={id}><i style={{background:lines[id].color}}/><span><strong>{id} · {lineName(id)}</strong><small>{lines[id].stationIds.length} {language==='uk'?'станцій':'stations'}</small></span><Icon name="chevron" size={18}/></button>)}</div>}</aside></div>
    <footer className="map-legend map-legend-v6"><span className="map-tip"><Icon name="info" size={15}/>{language==='uk'?'Підписи автоматично розставляються так, щоб не перекривати один одного та кнопки.':'Labels are placed automatically so they do not overlap each other or the controls.'}</span></footer>
  </section>
}
